/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module share.shared_types;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

struct SharedStruct {
  int key;
  string value;
  
  mixin TStructHelpers!([
    TFieldMeta(`key`, 1, TReq.OPT_IN_REQ_OUT),
    TFieldMeta(`value`, 2, TReq.OPT_IN_REQ_OUT)
  ]);
}

