/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module tutorial.Calculator;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import tutorial.tutorial_types;
import share.SharedService;

interface Calculator : SharedService {
  void ping();
  int add(int num1, int num2);
  int calculate(int logid, ref const(Work) w);
  void zip();

  alias tutorial.tutorial_types.InvalidOperation InvalidOperation;

  enum methodMeta = [
    TMethodMeta(`add`, 
      [TParamMeta(`num1`, 1), TParamMeta(`num2`, 2)]
    ),
    TMethodMeta(`calculate`, 
      [TParamMeta(`logid`, 1), TParamMeta(`w`, 2)],
      [TExceptionMeta(`ouch`, 1, `InvalidOperation`)]
    ),
    TMethodMeta(`zip`, 
      [],
      [],
      TMethodType.ONEWAY
    )
  ];
}
