/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module tutorial.tutorial_constants;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import tutorial.tutorial_types;

immutable(int) INT32CONSTANT;
immutable(string[string]) MAPCONSTANT;

static this() {
  INT32CONSTANT = 9853;

  MAPCONSTANT = cast(immutable(string[string])) {
    string[string] v;
    v["hello"] = "world";
    v["goodnight"] = "moon";
    return v;
  }();
}
